config/routes.rb
Rails.application.routes.draw do
  resources :resorts do 
    resources :lifts, except: [:show, :edit, :update]
  end

  resources :lifts, only: [:show, :edit, :update]

end

app/models/lift.rb
class Lift < ActiveRecord::Base
  belongs_to :resort
  validates :name, presence: true, uniqueness: true
  validates :seats, presence: true
end

app/models/resort.rb
class Resort < ActiveRecord::Base
  has_many :lifts, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true, uniqueness: true
  validates :trail_map_path, presence: true, uniqueness: true
  validates :average_season_accumulation, presence: true
  validates :rating, presence: true
  validates :review, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController 
  before_action :set_resort, only: [:index, :new, :create]
  before_action :set_lift, only: [:show, :edit, :update]
  def index
    @lifts = @resort.lifts.all
  end 

  def new
    @lift = @resort.lifts.new
  end

  def create 
    @lift = @resort.lifts.create(lift_params)
    redirect_to resort_lifts_path
  end 

  def show
  end 

  def edit
  end 

  def update
    if @lift.update(lift_params)
      redirect_to resorts_path
    else 
      render :edit
    end
  end 

  private 

  def lift_params
    params.require(:lift).permit(:name, :seats)
  end 

  def set_resort
    @resort = Resort.find(params[:resort_id])
  end

  def set_lift
    @lift = Lift.find(params[:id])
  end
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
  before_action :set_resort, only: [:show, :edit, :update, :destroy]
  def index
    @resorts = Resort.all
  end

  def new
    @resort = Resort.new
  end

  def create
    @resort = Resort.create(resort_params)
    if @resort.save
      redirect_to @resort
    else 
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @resort.update(resort_params)
     redirect_to @resort
    else
      render :edit
    end
  end

  def destroy
    @resort.destroy
    redirect_to resorts_path
  end

  private 

  def resort_params
    params.require(:resort).permit(:name, :image_path, :trail_map_path, :average_season_accumulation, :total_accumulation, :total_base, :rating, :review)
  end 

  def set_resort
    @resort = Resort.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resort Reporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lifts/_form.html.erb
<%= form_for(@lift) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :seats %>
  <%= f.text_field :seats %>

  <%= f.submit %>

<% end %>

app/views/lifts/edit.html.erb
<h1>Edit <%= @lift.name %></h1>
<%= render partial: "form" %> 

app/views/lifts/index.html.erb
<h1>Lifts at <%= @resort.name %></h1>

<ol>
  <% @lifts.each do |lift| %>
    <li>
        <%= link_to lift.name, lift %>
        <%= lift.seats %> Seats
    </li>
  <%end%>
</ol>

<ul>
  <li><%= link_to "Add Lift", new_resort_lift_path(@resort) %></li>
  <li><%= link_to "Home", resorts_path %></li>
</ul>

<%= image_tag @resort.trail_map_path %>

app/views/lifts/new.html.erb
<h1>New Lift</h1>
<h5>Add a new lift for <%= @resort.name %></h5> 
<%= form_for ([@resort, @lift]) do |f| %>
  <%= f.label :name %> 
  <%= f.text_field :name %> 

  <%= f.label :seats %>
  <%= f.text_field :seats %> 

  <%= f.submit %>
<% end %> 

app/views/lifts/show.html.erb
<h1><%= @lift.name %></h1>
<h3><%= @lift.seats %> Seats</h3>

<ul>
  <li><%= link_to @lift.resort.name, resort_path(@lift.resort) %>
  <li><%= link_to "Edit Lift", edit_lift_path(@lift) %> 
</ul>

app/views/resorts/_form.html.erb
<%= form_for(@resort) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.label :trail_map_path %>
  <%= f.text_field :trail_map_path %>

  <%= f.label :average_season_accumulation %>
  <%= f.text_field :average_season_accumulation %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.label :review %>
  <%= f.text_field :review %>

  <%= f.submit %>

<% end %>

app/views/resorts/edit.html.erb
<h1>Edit <%= @resort.name %> Resort</h1>

<%= render partial: "form" %> 

app/views/resorts/index.html.erb
<h1>All Resorts</h1>
<ol>
<% @resorts.each do |resort| %> 
  <li> <%= link_to resort.name, resort %> </li>
  <% end %>
</ol>

<%= link_to "New Resort", new_resort_path %>

app/views/resorts/new.html.erb
<h1>Add A New Resort</h1>

<%= render partial: "form" %> 

app/views/resorts/show.html.erb
<%= image_tag @resort.image_path %>
<h3> Overall Rating: <%= @resort.rating %> </h3>
<h3> Average Yearly Snow Accumulation: <%= @resort.average_season_accumulation %> inches</h3> 

<ul>
  <li><%= link_to "View Lifts", resort_lifts_path(@resort) %></li>
  <li><%= link_to "Edit Resort", edit_resort_path(@resort) %></li>
  <li><%= link_to "All Resorts", resorts_path %></li>
</ul>

<ul>
  <li><%= link_to "Delete", resort_path(@resort), method: :delete %></li>
</ul>